Carbon:
  Image:
    dummy:
      color: '#970C1D'
  IncludeAssets:
    GoogleFonts: Ubuntu:300,400,400i
    Packages:
      aa_Theme:
        General:
          Head:
            - DistributionPackages/Queo.SitePackage/Resources/Private/Assets/Main.js[defer]
            - Main.css
        Backend:
          Head:
            - Backend.css
